module.exports = {
  up: queryInterface => queryInterface.bulkInsert('Orders', [
    {
      date: '2018-05-16',
      amount: 1100,
      quantity: 1,
      userId: 1,
      mealId: 1,
      status: 'pending',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      date: '2018-05-16',
      amount: 1500,
      quantity: 1,
      userId: 1,
      mealId: 2,
      status: 'cancelled',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      date: '2018-05-16',
      amount: 1200,
      quantity: 1,
      userId: 2,
      mealId: 3,
      status: 'pending',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      date: '2018-05-16',
      amount: 1500,
      quantity: 1,
      userId: 3,
      mealId: 3,
      status: 'delivered',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      date: '2018-05-17',
      amount: 1500,
      quantity: 1,
      userId: 2,
      mealId: 5,
      status: 'pending',
      createdAt: '2018-05-17T05:50:23.499Z',
      updatedAt: new Date(),
    },
    {
      date: '2018-05-24',
      amount: 1500,
      quantity: 1,
      userId: 2,
      mealId: 5,
      status: 'pending',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ], {}),

  down: queryInterface => queryInterface.bulkDelete('Orders', null, {}),
};
